# Generated by Django 5.2 on 2026-09-05 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified_badge',
            field=models.BooleanField(default=False, help_text="Shows the 'Verified Agent' badge. Set only when an admin approves this agent's AgentVerification submission (NIN/BVN/CAC + documents) - separate from agent_status, which only gates whether they can list properties at all."),
        ),
        migrations.CreateModel(
            name='AgentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin_number', models.CharField(blank=True, max_length=20)),
                ('bvn_number', models.CharField(blank=True, max_length=20)),
                ('cac_number', models.CharField(blank=True, help_text='Optional - for registered businesses.', max_length=20)),
                ('id_document', models.FileField(help_text="A valid government-issued ID matching the NIN/BVN provided (e.g. National ID card, driver's license, voter's card).", upload_to='verification_documents/id/')),
                ('cac_document', models.FileField(blank=True, help_text='Optional - CAC certificate, if a CAC number was provided.', null=True, upload_to='verification_documents/cac/')),
                ('proof_of_address', models.FileField(blank=True, help_text='Optional - a utility bill or tenancy agreement showing the office/home address.', null=True, upload_to='verification_documents/address/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='accounts_ag_status_cb395a_idx')],
            },
        ),
    ]
