# Generated by Django 5.2 on 2026-08-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether notification emails are sent to this user. Toggled from Settings.'),
        ),
    ]
