# Generated by Django 6.1 on 2026-08-11 15:26

import django.core.validators
import django.db.models.deletion
import properties.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'LGA',
                'verbose_name_plural': 'LGAs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('property_type', models.CharField(choices=[('Mini Flat', 'Mini Flat'), ('Self-Contain', 'Self-Contain'), ('1-Bedroom Flat', '1-Bedroom Flat'), ('2-Bedroom Flat', '2-Bedroom Flat'), ('3-Bedroom Flat', '3-Bedroom Flat'), ('4-Bedroom Flat', '4-Bedroom Flat'), ('5+-Bedroom Flat', '5+ Bedroom Flat'), ('Duplex', 'Duplex'), ('Bungalow', 'Bungalow'), ('Terrace', 'Terrace'), ('Mansion', 'Mansion'), ('Commercial Space', 'Commercial Space'), ('Office Space', 'Office Space'), ('Warehouse', 'Warehouse'), ('Shop', 'Shop')], max_length=50)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('toilets', models.IntegerField(blank=True, default=1, null=True)),
                ('property_size', models.CharField(blank=True, help_text='e.g. 500 sqm', max_length=50, null=True)),
                ('area', models.CharField(help_text='Specific Area/Neighborhood', max_length=200)),
                ('address', models.TextField(blank=True, help_text='Full street address', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rental_period', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], default='yearly', max_length=20)),
                ('service_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('agency_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('legal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('caution_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('agreement_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('other_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('other_fees_description', models.CharField(blank=True, max_length=200, null=True)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_water', models.BooleanField(default=False)),
                ('has_electricity', models.BooleanField(default=False)),
                ('has_borehole', models.BooleanField(default=False)),
                ('has_generator', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_fenced_compound', models.BooleanField(default=False)),
                ('is_furnished', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('has_internet', models.BooleanField(default=False)),
                ('has_cctv', models.BooleanField(default=False)),
                ('has_swimming_pool', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('other_amenities', models.TextField(blank=True, help_text='Other amenities not listed above', null=True)),
                ('agent_name', models.CharField(max_length=200)),
                ('agent_whatsapp', models.CharField(help_text='Format: 234XXXXXXXXXX', max_length=20)),
                ('agent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='property_videos/', validators=[properties.validators.validate_video_file])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('RENTED', 'Rented'), ('ARCHIVED', 'Archived')], default='PENDING_REVIEW', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('whatsapp_clicks', models.PositiveIntegerField(default=0)),
                ('favourite_count', models.PositiveIntegerField(default=0)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('rented_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_properties', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.state')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', validators=[properties.validators.validate_image_file])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='property_thumbnails/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order_index', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order_index', 'uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='properties.state'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties__status_6427a0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['state'], name='properties__state_i_2df2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['lga'], name='properties__lga_id_133f69_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='properties__propert_5c7790_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bedrooms'], name='properties__bedroom_6cd35c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='properties__created_72ecc3_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'state'], name='properties__status_75a2be_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'property_type'], name='properties__status_e02930_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'created_at'], name='properties__status_8e4eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_by', 'status'], name='properties__created_b6c746_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['featured', 'status'], name='properties__feature_eedab8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lga',
            unique_together={('state', 'name')},
        ),
    ]
