# Generated by Django 4.2.30 on 2026-07-28 07:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import properties.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('area', models.CharField(help_text='Specific Area/Neighborhood', max_length=200)),
                ('property_type', models.CharField(choices=[('Mini Flat', 'Mini Flat'), ('Self-Contain', 'Self-Contain'), ('1-Bedroom Flat', '1-Bedroom Flat'), ('2-Bedroom Flat', '2-Bedroom Flat'), ('3-Bedroom Flat', '3-Bedroom Flat'), ('Duplex', 'Duplex'), ('Bungalow', 'Bungalow'), ('Terrace', 'Terrace'), ('Mansion', 'Mansion'), ('Commercial Space', 'Commercial Space')], max_length=50)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('agent_name', models.CharField(max_length=200)),
                ('agent_whatsapp', models.CharField(help_text='Format: 234XXXXXXXXXX', max_length=20)),
                ('agent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='property_videos/', validators=[properties.validators.validate_video_file])),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('DRAFT', 'Draft')], default='PENDING_REVIEW', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('whatsapp_clicks', models.IntegerField(default=0)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_properties', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.lga')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', validators=[properties.validators.validate_image_file])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='property_thumbnails/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order_index', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.state'),
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='properties.state'),
        ),
        migrations.AlterUniqueTogether(
            name='lga',
            unique_together={('state', 'name')},
        ),
    ]
