# Generated by Django 5.2 on 2026-09-06 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'state', 'lga', 'price'], name='properties__status_3fbe37_idx'),
        ),
    ]
