# Generated by Django 5.2 on 2026-09-03 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fake_listing', 'Fake Listing'), ('wrong_price', 'Wrong Price'), ('unavailable', 'Unavailable Property'), ('suspicious_agent', 'Suspicious Agent'), ('misleading_info', 'Misleading Information'), ('inappropriate_content', 'Inappropriate Content'), ('other', 'Other Issue')], default='other', max_length=30)),
                ('description', models.TextField(help_text='Please provide details about the issue.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for administrators.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='properties.property')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='reports_rep_status_7dd5e5_idx'), models.Index(fields=['category'], name='reports_rep_categor_b7680f_idx'), models.Index(fields=['reporter'], name='reports_rep_reporte_101677_idx'), models.Index(fields=['property'], name='reports_rep_propert_de90cc_idx'), models.Index(fields=['agent'], name='reports_rep_agent_i_5a9735_idx')],
            },
        ),
    ]
