# Generated by Django 5.2 on 2026-08-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('agent_approved', 'Agent Approved'), ('agent_rejected', 'Agent Rejected'), ('agent_suspended', 'Agent Suspended'), ('property_approved', 'Property Approved'), ('property_rejected', 'Property Rejected'), ('property_published', 'Property Published'), ('new_message', 'New Message'), ('inspection_request', 'Inspection Request'), ('inspection_accepted', 'Inspection Accepted'), ('inspection_declined', 'Inspection Declined'), ('inspection_completed', 'Inspection Completed'), ('report_submitted', 'Report Submitted'), ('report_resolved', 'Report Resolved'), ('system', 'System')], default='system', max_length=30),
        ),
    ]
